version: "3.9"
services:
  python:
    build: 
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"