name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v2
      name: Build the Docker image
      with:
          context: .
          file: ./Dockerfile
      run: docker build . --file Dockerfile --tag test-image:$(date +%s)
