name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        #uses: actions/checkout@v2
        name: Build the Docker image
        with:
            context: ./python
            file: ./Dockerfile
        run: docker build . --tag test-image:$(date +%s)
