name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cd python
    - name: Build python docker container
      run: docker build -t michael/python .
    # - name: Build the Docker images
    #   run: docker compose up -d --build
    # - name: Stop the Docker images
    #   run: docker compose down
